title: 'Demo Apps'
shared:
  - name: 'Demo Apps'
    batch: 'quick'
    cluster: 'oakley'
    node:
      - type: 'oakley'
        ppn: 3
    webserver?: true
    pbs:
      envvars:
        COMSOL_MODULE: 'comsol/52a_server'
        COMSOL_APP_TOKEN: 'awesim_altasim_demo'
        COMSOL_APP_ROOT: '/users/PZS0645/wiag/comsol/applications/altasim/demo'
